name: Deploy

on:
  push:
    branches:
      - 'pin-ipfs-cid'

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install node
          uses: actions/setup-node@v1
          with:
            node-version: 14
        - name: setup ipfs
          uses: ibnesayeed/setup-ipfs@master
          with:
            run_daemon: true
        - name: Install ipfs-cluster-ctl
          run: |
            wget https://dist.ipfs.io/ipfs-cluster-ctl/v0.14.1/ipfs-cluster-ctl_v0.14.1_linux-amd64.tar.gz
            tar xvfz ipfs-cluster-ctl_v0.14.1_linux-amd64.tar.gz
        - name: pin on cluster
          env: 
            IPFS_CLUSTER_BASIC_AUTH: ${{ secrets.IPFS_CLUSTER_BASIC_AUTH }}
            IPFS_CLUSTER_HOST: ${{ secrets.IPFS_CLUSTER_HOST }}
          run: |
            cat ./cids | while read CID; do
              $GITHUB_WORKSPACE/ipfs-cluster-ctl/ipfs-cluster-ctl --basic-auth $IPFS_CLUSTER_BASIC_AUTH --host "$IPFS_CLUSTER_HOST" pin add $CID
            done
